# Generated by Django 3.2.5 on 2021-07-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('unique_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('request_time', models.DateTimeField()),
                ('response_time', models.DateTimeField(default=None, null=True)),
                ('request_data_type', models.CharField(max_length=10)),
                ('request_single_data', models.CharField(default=None, max_length=500, null=True)),
                ('request_bulk_data', models.FileField(default=None, null=True, upload_to='')),
                ('response_data', models.CharField(default=None, max_length=500, null=True)),
                ('response_status_code', models.CharField(default=None, max_length=10, null=True)),
                ('response_message', models.CharField(default=None, max_length=500, null=True)),
                ('completion_status', models.CharField(default='Incomplete', max_length=20)),
            ],
        ),
    ]
