# Generated by Django 3.2.5 on 2022-07-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender_classification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestresponse',
            name='response_probability',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
